import Head from "next/head";
import { Inter } from "next/font/google";
import { PostCard, PostWidget } from "../../components";
import { getPost } from "../../services";

const inter = Inter({ subsets: ["latin"] });
const posts = [
  {
    id: "1",
    title: "MERN Stack  Pracktikum",
    excerpt: "MongoDB, ExpressJS, ReactJS, NodeJS",
  },
  {
    id: "2",
    title: "Digital Marketing",
    excerpt: "Instagram, Telegram, Twitch, Twitter",
  },
];

export default function Home({posts}) {
  return (
    <div className="container mx-auto px-10 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12  ">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => (
            <PostCard key={post.node.author.id} post={post.node} />
            
          ))}
        </div>
      </div>
      <div className="lg:col-span-4 col-span-1">
        <div className="lg:sticky relative top-8">
          <PostWidget />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPost()) || [];

  return {
    props: {posts}
  }
}
